[FIX] compilation error due to isspace()
HINT: resolves error: array subscript has type 'char'
[-Werror=char-subscripts] as all warnings are treated as errors